version: "3.8"
services:
  app:
    container_name: croce_russo  # Nome personalizzato del container
    build:
      context: .  
      dockerfile: Dockerfile
    image: croce_russo  # Nome personalizzato dell'immagine
    volumes:
      - .:/app  # Monta la cartella locale nel container
    command: ["python", "ProvaScript.py"]